### ISSUE TITLE
DIPPR 801 2019?

### ISSUE THREAD

**Issue by longemen3000** [CalebBell/chemicals#20]
it is posible to add the DIPPR 801 2019 to the list of available databases?, i have access and  can produce the corresponding TSVs

**Comment by CalebBell** [comment]
Hi Andrés,
It is definitely not possible. That is a proprietary database, to my knowledge any license to use it would include an EULA forbidding replicating it unless given an exemption. Sometimes they publish their data publicly in to books (like Perry's), and sometimes in research papers by authors with exceptions. It is only from those legitimate sources that data will be included into `chemicals`, barring the DIPPR deciding to make their database non-commercial :)
Sincerely,
Caleb
