### ISSUE TITLE
conda-forge Package Missing

### ISSUE THREAD

**Issue by danieldjewell** [CalebBell/chemicals#21]
Hi!

I'm guessing you probably already know this, but this package is missing from the ```conda-forge``` channel ... (Is that what the ```#TODO: Conda install ``` note meant? I guess I didn't interpret it that way. )

If that's the case, maybe in the interim ~~strikethrough~~ the conda section? (In Github Markdown it's two tildes ~ on either side :grin: ) 

Thanks for the clarification!

**Comment by CalebBell** [comment]
Hi Daniel,

@volpatto created the conda packages for my other packages. I'm not likely going to get to doing it personally soon as pip works pretty well and there are lots of big-ticket items on my plate.

Cheers,
Caleb

**Comment by volpatto** [comment]
Hey, guys!

I think I can add `chemicals` there, I just have to manage to find some time to do so. @danieldjewell do you need `chemicals` from `conda-forge` urgently? I think I can add this package to `conda-forge` in the next weeks.

Cheers!

**Comment by CalebBell** [comment]
Hi Diego,
I received another request for this over email. Do you know when you may have time to package chemicals?
Sincerely,
Caleb

**Comment by volpatto** [comment]
> Hi Diego,
> I received another request for this over email. Do you know when you may have time to package chemicals?
> Sincerely,
> Caleb

Hi, Caleb.

Nice! I can't give you an exact day, but I estimate that I will pack `chemicals` next week. If I manage to find some time, maybe I can begin this upcoming weekend.

Cheers,
Diego

**Comment by CalebBell** [comment]
The package is now available on conda-forge!
