### ISSUE TITLE
Update GWPs for IPCC Report version 5

### ISSUE THREAD

**Issue by CalebBell** [CalebBell/chemicals#23]
**Is your feature request related to a problem? Please describe.**
The GWP lookups do not have updated data for the IPCC report from 2012. It is important to update the data to include the new values.

**Do you acknowledge the project is developed by volunteers adding features primarily for their own purposes?**
Yes, and I have a purpose for it.

**Additional context**
Table can easily be copied from this official PDF:
https://www.sealevel.info/AR5_Table_8.A.1_Lifetimes_Radiative_Efficiencies_and_Metric_values_pp_731-738.pdf
Will likely simply update the existing file which is loaded to include the new values. Likely should update the default method to use the new values.

**Comment by CalebBell** [comment]
@yoelcortes Thank you for bringing this topic back up! My normal tools are [Okular](https://okular.kde.org/) which has a great table extractor feature and [ScanTailor](https://github.com/scantailor/scantailor) although this one is digital already so no scanning is necessary. 

I can help with this task also. Attached is the extracted data from the PDF as a spreadsheet in a table. The "work items" are as follows as they look to me now:

- Obtain the CAS numbers for each component. This is the slowest part in my experience.
- Convert lifetimes which are in days into floating-point fractional years.
- Make column headers consistent between the GWP files.
- Decide if the AGWP values should be included.
- Remove empty rows.
- Decide what to do about "<1" values.
- Add the file
- Modify the code
- Add a couple tests
- (maybe) change the default to the new values.

[GWP 5e.xlsx](https://github.com/CalebBell/chemicals/files/7230380/GWP.5e.xlsx)

I hope the spreadsheet is helpful. Thank you for your continued collaboration. Splitting out Chemicals into its own project was definitely a good call.

**Comment by yoelcortes** [comment]
@CalebBell, I didn't realize this issue was already opened. This is a ton of help! The task list sounds good, I got it from here. Thanks again!
