### ISSUE TITLE
Get chemical name from chemical notation

### ISSUE THREAD

**Issue by Python3-8** [CalebBell/chemicals#31]
```py
>>> from chemicals import *
>>> h2co3_from_name = CAS_from_any('Carbonic Acid')
>>> h2co3_from_notation = CAS_from_any('h2co3')
>>> h2co3_from_name == h2co3_from_notation # True
>>> get_name(h2co3_from_notation) # is there something I can use to do something like this and get "Carbonic Acid"?
```

Also, may I know the difference between `CAS_from_any('h2co3')` and `CAS_from_any('H2CO3')`? They seem to return different results: `'463-79-6'`, and `'107-32-4'`.

**Comment by longemen3000** [comment]
107-32-4:  https://en.wikipedia.org/wiki/Performic_acid , formula = CH2O3
63-79-6:   https://en.wikipedia.org/wiki/Carbonic_acid , formula = CH2O3
the main problem is that a search by formula is not unique

**Comment by CalebBell** [comment]
Hi Pranav,
Andrés is exactly correct! The synonyms are from pubchem and unexpected things happen sometimes, like h2co3 resolving to something different than CH2O3. I strongly recommend avoiding searching by formula.
You can retrieve more information about a chemical with the method search_chemical; i.e. the name can be found with a query like:

```
>>> search_chemical('carbonic acid').common_name
"carbonic acid"
```
Sincerely,
Caleb

**Comment by CalebBell** [comment]
Your question has inspired me to begin working on documentation for the project again. 
https://chemicals.readthedocs.io/tutorial.html may provide assistance as well. Thank you, Andrés, for your help with this!
