### ISSUE TITLE
Nitrogen Lennard-Jones values missing

### ISSUE THREAD

**Issue by jgostick** [CalebBell/chemicals#38]
What is the chemical's pubchem ID? CAS: 7727-37-9'

What is its formula? N2

The lennard_jones.Stockmayer and molecular_diameter values are missing for nitrogen.  I am currently adding them by hand, but it'd be helpful if you could include them.  I am using these values:  (s=3.788, e_k=71.4), though I forget where I found them.

**Comment by CalebBell** [comment]
Hi Jeff,
I added the values from the following source:

Poling, Bruce E. The Properties of Gases and Liquids. 5 edition. New York: McGraw-Hill Professional, 2000.

The specific values were s=3.798 and e_k=71.4. This is released in chemcials 1.0.15; which is on pypi now and will be available in Conda usually within a day.

Cheers,
Caleb

**Comment by jgostick** [comment]
great!  Now we can compute the D_AB for oxygen in air 👍
