### ISSUE TITLE
Adding chemical ID: 157846

### ISSUE THREAD

**Issue by marcocaggioni** [CalebBell/chemicals#48]
What is the chemical's pubchem ID?
157846

What is its formula?
"isosmiles": "CCCCCCCCCCCCCCCCCCCCCC[N+](C)(C)C.COS(=O)(=O)[O-]",

This is the Json from pubchem:

[
	{
		"cid": "157846",
		"cmpdname": "Behentrimonium methosulfate",
		"cmpdsynonym": ["Behentrimonium methosulfate","81646-13-1","Docosyltrimethylammonium methyl sulphate","docosyl(trimethyl)azanium;methyl sulfate","5SHP745C61","Behenyl trimethyl ammonium methosulfate","UNII-5SHP745C61","EINECS 279-791-1","EC 279-791-1","SCHEMBL126381","DTXSID00231231","BEHENTRIMONIUM METHOSULPHATE","behenyltrimethylammonium methyl sulfate","BEHENTRIMONIUM METHOSULFATE [INCI]","N,N,N-Trimethyl-1-docosanaminium methosulfate","BEHENYL TRIMETHYL AMMONIUM METHOSULPHATE","1-Docosanaminium, N,N,N-trimethyl-, methosulfate","Q27262812"],
		"mw": "479.800",
		"mf": "C26H57NO4S",
		"polararea": "74.800",
		"complexity": "344.000",
		"heavycnt": "32",
		"hbonddonor": "0",
		"hbondacc": "4",
		"rotbonds": "21",
		"inchi": "InChI=1S/C25H54N.CH4O4S/c1-5-6-7-8-9-10-11-12-13-14-15-16-17-18-19-20-21-22-23-24-25-26(2,3)4;1-5-6(2,3)4/h5-25H2,1-4H3;1H3,(H,2,3,4)/q+1;/p-1",
		"isosmiles": "CCCCCCCCCCCCCCCCCCCCCC[N+](C)(C)C.COS(=O)(=O)[O-]",
		"canonicalsmiles": "CCCCCCCCCCCCCCCCCCCCCC[N+](C)(C)C.COS(=O)(=O)[O-]",
		"inchikey": "QIVLQXGSQSFTIF-UHFFFAOYSA-M",
		"iupacname": "docosyl(trimethyl)azanium;methyl sulfate",
		"exactmass": "479.401",
		"monoisotopicmass": "479.401",
		"charge": "0",
		"covalentunitcnt": "2",
		"isotopeatomcnt": "0",
		"totalatomstereocnt": "0",
		"definedatomstereocnt": "0",
		"undefinedatomstereocnt": "0",
		"totalbondstereocnt": "0",
		"definedbondstereocnt": "0",
		"undefinedbondstereocnt": "0",
		"pclidcnt": "0",
		"gpidcnt": "3818",
		"gpfamilycnt": "1390",
		"neighbortype": "2D",
		"annothits": ["Classification","Patents","Safety and Hazards","Use and Manufacturing"],
		"annothitcnt": "4",
		"cidcdate": "2005-08-08",
		"sidsrcname": ["A2B Chem","AA BLOCKS","ABI Chem","Alfa Chemistry","BenchChem","ChemIDplus","Chemieliva Pharmaceutical Co., Ltd","ChemSpider","ChemTik","Cooke Chemical Co., Ltd","CymitQuimica","DiscoveryGate","Egon Willighagen, Department of Bioinformatics - BiGCaT, Maastricht University","EPA DSSTox","FDA Global Substance Registration System (GSRS)","Google Patents","Hairui Chemical","J&H Chemical Co.,ltd","labseeker","NextBio","NORMAN Suspect List Exchange","PATENTSCOPE (WIPO)","RR Scientific","Smolecule","SureChEMBL","THE BioTek","Thomson Pharma","ToxPlanet","Wikidata","Yick-Vic Chemicals & Pharmaceuticals (HK) Ltd."],
		"depcatg": ["Chemical Vendors","Curation Efforts","Governmental Organizations","Journal Publishers","Legacy Depositors","Research and Development","Subscription Services"]
	}
]

Is there a procedure to do this manually and create a local list of extra chemicals not present in the library?
would be nice to have a method to import from pubchem json format but not sure how complex would be.
Happy to help if you can give me some guidance.

thanks
    Marco

**Comment by CalebBell** [comment]
Hello,
It has been quite some time but I have the scripts for adding/removing/editing chemical metadata working again (ported to python 3, working with new versions of pubchem & common chemistry integration)
I have resolved the issue. The chemical metadata has been added for this chemical. It is in the new chemicals release 1.3.1.
Sincerely,
Caleb
