### ISSUE TITLE
The attribute "ionization" is listed twice with different descriptions

### ISSUE THREAD

**Issue by arnoudbuzing** [CalebBell/chemicals#50]
On this page:

https://chemicals.readthedocs.io/chemicals.elements.html#module-chemicals.elements

The attribute "ionization" is listed twice with different descriptions:

![image](https://github.com/CalebBell/chemicals/assets/3236874/0fc5da7d-7876-49d2-89cd-f68bfe113f5d)

**Comment by CalebBell** [comment]
Thank you, Arnoud! The second one was electron affinity. 
Caleb
