### ISSUE TITLE
documentation: incorrect latex rendering

### ISSUE THREAD

**Issue by longemen3000** [CalebBell/chemicals#51]
**Describe the bug**
chemicals.heat_capacity.PPDS2 does not render their latex equation correctly:
![image](https://github.com/CalebBell/chemicals/assets/38795484/ab8109f6-1b7f-4dba-88d5-5b1adf6faed3)

**Minimal Reproducible Example**
https://chemicals.readthedocs.io/chemicals.heat_capacity.html#chemicals.heat_capacity.PPDS2

**Comment by CalebBell** [comment]
Hi Andrés,
Thank you for pointing out this error. I have corrected it. 
Sincerely,
Caleb
